export default {
  // Issue reducer
  ADD_ISSUE_TO_LIST: 'ADD_ISSUE_TO_LIST',
  // User reducer
  ADD_USER_TO_LIST: 'ADD_USER_TO_LIST',

  EDIT_ISSUE: 'EDIT_ISSUE',

  DELETE_ISSUE: 'DELETE_ISSUE',

  ADD_LISTCOLUMN: 'ADD_LISTCOLUMN',

  DELETE_COLUMN: 'DELETE_COLUMN',

  DELETE_USER: 'DELETE_USER',
};
